// checksum 0xfde6 version 0x90005
/*
  This file was generated by the Qt Quick 2 Application wizard of Qt Creator.
  QtQuick2ApplicationViewer is a convenience class containing mobile device specific
  code such as screen orientation handling. Also QML paths and debugging are
  handled here.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef QTQUICK2_VIEWER_H
#define QTQUICK2_VIEWER_H

#include <QtQuick/QQuickView>

class QtQuick2ViewerPrivate;

class QtQuick2Viewer : public QQuickView
{
    Q_OBJECT

public:
    explicit QtQuick2Viewer(QWindow *parent = 0);
    virtual ~QtQuick2Viewer();

    void setMainQmlFile(const QString &file);
    void addImportPath(const QString &path);
    void printImportPathList();

    void showExpanded();

    void hideExpanded();


signals:
    void viewExpose();
    void viewMinilize();
    void viewResize();
    void viewShow();

protected:
    void exposeEvent(QExposeEvent *ev);
    void resizeEvent(QResizeEvent *ev);
    void showEvent(QShowEvent *ev);

private:
    QtQuick2ViewerPrivate *d;
};

#endif // QTQUICK2_VIEWER_H
